############################### Basic Information ###############################
info:
  name: Volantis
  version: '2.0.2'
  docs: https://volantis.js.org/
  cdn: # To use CDN, write 'use_cdn: true' in 'blog/_config.yml'.
    css: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0.2.4/css/style.css
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0.2.4/js/app.js


############################### Style ###############################
style:
  max_width: 1080px # Sum of body width and sidebar width
  navbar:
    height: 64px
    effect: [shadow, blur] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
    highlight:
      language: false # show language of codeblock
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
  gap:
    h2: 2.5em # Spacing above H2
    h3: 1.5em # Spacing above H3
    h4: 1em # Spacing above H4
    line: 1rem # Paragraph spacing
    inline: .5rem # Paragraph spacing within a block
  fontfamily:
    bodyfont:
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    # codefont:
    #   name: 'Monaco'
    #   url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
    #   weight: normal
    #   style: normal
  color:
  #   site: '#21232F' # Website background color
  #   card: '#444' # Card background color
  #   text: '#fff' # The color of the text on the card.
    theme: '#197b30' # Main color
  #   link: '#1BCDFC' # Link color
  #   hover: '#ff5722' # Link highlight color
  #   inner: '#333' # Text color inside the button
  #   block: '#555' # Block color
  #   inlinecode: yellow # Inline code color
  #   codeblock: '#555' # Codeblock color
  #   p: '#ccc' # Paragraph color




############################### Layout ###############################
cover:
  scheme: docs # docs, blog
  display:
    home: false
    archive: false
    others: false # can be written in front-matter 'cover: true'
  logo: # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/256/google_logo.png
  title: <red>Shan</red><green>San</green>
  subtitle: '迷途者的港湾,<blue>寻我所想</blue>'
  search: 寻你所想 # search bar placeholder
  features:
    - name: 文档
      icon: fas fa-book
      url: https://volantis.js.org/getting-started/
    - name: 博文
      icon: fas fa-rss
      url: https://volantis.js.org/archives/
    - name: 示例
      icon: fas fa-play-circle
      url: https://volantis.js.org/examples/
    - name: 源码
      icon: fas fa-file-code
      url: https://github.com/xaoxuu/hexo-theme-volantis/
      rel: external nofollow noopener noreferrer
      target: _blank
    - name: 鸣谢
      icon: fas fa-handshake
      url: https://volantis.js.org/contributors/


# Navigation Bar
navbar:
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title: <green>Shan San</green>
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    # This menu will be displayed on the laptop or desktop.
    on_desktop:
      - name: 博客
        icon: fas fa-rss
        url: /
      - name: 分类
        icon: fas fa-folder-open
        url: categories/
      - name: 归档
        icon: fas fa-archive
        url: archives/
      - name: Github
        icon: fab fa-github-square
        url: https://github.com/yeshan333
      - name: 友链
        icon: fas fa-link
        url: friends/
      - name: 关于
        icon: fas fa-info-circle
        url: about/
      - name: slides
        icon: fab fa-slideshare
        url: https://slide.shan333.cn
      - name: 中国蟒
        icon: fab fa-python
        url: PyChina/
    # This menu will be displayed on the mobile.
    on_mobile:
      - name: 博客
        icon: fas fa-rss
        url: /
      - name: 分类
        icon: fas fa-folder-open
        url: categories/
      - name: 标签
        icon: fas fa-tags
        url: tags/
      - name: 归档
        icon: fas fa-archive
        url: archives/
      - name: 友链
        icon: fas fa-link
        url: friends/
      - name: 关于
        icon: fas fa-info-circle
        url: about/
  search: 寻你所想   # Search bar placeholder



layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, date, category, tags, top]
    # 列表类页面的侧边栏
    sidebar: [blogger, custom_nav, category, tagcloud, qrcode, wonderful_link, my_follow]
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, category, date, counter, top]
      footer: [updated, tags, btns, share]
    # 文章页面的侧边栏
    sidebar: [qrcode, toc]
  # 文章布局，参数继承自 on_page
  on_post:
    # 文章页脚，自动在每一篇文章末尾添加
    article_footer: [copyright, donate]
  # 其他的页面布局暂时等于 on_list


# meta library
meta:
  # 文章标题
  title: # 暂无配置
  # 默认文章作者（可在front-matter中覆盖）
  author:
    avatar: https://img.vim-cn.com/a3/caa9ef084c4f562b82b1cca6e978c0dca58c5f.png
    name: yeshan333
    url: https://github.com/yeshan333
  # 文章创建日期
  date:
    icon: fas fa-edit
    title: '文章首发于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-save
    title: '最近更新时间：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章置顶
  top:
    icon: fas fa-angle-double-up
  # 文章浏览计数
  counter:
    icon: fas fa-eye
  # 文章字数和阅读时长
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-tags
  # 分享
  share:
    - id: qq
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
    - id: qzone
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qzone.png
    - id: weibo
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
    # - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
    #   img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/wechat.png
  # 链接
  btns:
    edit:
      icon: fas fa-edit
      title: 在GitHub上编辑此页
      color: '#888'
    repo: # https://www.baidu.com
      icon: fas fa-file-code
      title: 源码
      color: '#508EF2'
    bug: # https://www.baidu.com
      icon: fas fa-bug
      title: BUG
      color: '#FE5F58'
    doubt: #https://www.baidu.com
      icon: fas fa-question-circle
      title: 疑问
      color: '#FFBD2B'
    idea: # 建议链接
      icon: fas fa-lightbulb
      title: 建议
      color: '#3DC550'
    faq:
      icon: fas fa-comments
      title: FAQ
      color: '#29B1C9'
    feedback:
      icon: fas fa-comment-dots
      title: 反馈
      color: '#1BCDFC'

# widget library
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  blogger:
    class: blogger
    display: [desktop] # [desktop, mobile]
    avatar: https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn/try20200311205451.jpg
    title:
    subtitle:
    jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 本文目录
    list_number: false
    min_depth: 1
    max_depth: 5
  # ---------------------------------------
  # category widget
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /categories/
  # ---------------------------------------
  # tagcloud widget
  tagcloud:
    class: tagcloud
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: 热门标签
      url: /tags/
    min_font: 14
    max_font: 24
    color: true
    start_color: '#999'
    end_color: '#555'
  # ---------------------------------------
  # related posts widget
  related_posts:
    class: related_posts # npm i -S hexo-related-popular-posts
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-bookmark
      title: 相关文章
    max_count: 5
  # ---------------------------------------
  # copyright widget (valid only in articles)
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true
    permalink: '本文永久链接是：'
    content:
      - '<li>博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议</li>'
      # - permalink
  # ---------------------------------------
  # qrcode widget
  donate:
    class: qrcode
    display: [desktop, mobile] # [desktop, mobile]
    height: 64px  # Automatic height if not set
    fancybox: true
    images:
      - https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn@master/mmqrcode1583939866281.png
      - https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn@master/qrcode_1583939933465.jpg
  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/
  wonderful_link:
    class: list
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-medal
      title: 精选链接
      url:
    rows:
      - name: Material X
        desc: Hexo博客主题
        icon: fas fa-cube
        url: https://xaoxuu.com/wiki/material-x/
      - name: 关于我 / 留言板
        icon: fas fa-comment-dots
        url: /about/
      - name: Collect
        icon: fab fa-delicious
        url: /Collect/
      - name: shan_pic
        icon: fas fa-images
        url: https://img.shan333.cn
      - name: 每日天文一图
        avatar: https://apod.nasa.gov/favicon.ico
        url: https://apod.nasa.gov/apod/astropix.html
      - name: Carbon
        avatar: https://img.vim-cn.com/76/a8416146154b60cbaa432ad3cf3b919190e1d8
        url: https://carbon.now.sh
      - name: 雨落无声
        avatar: https://s2.ax1x.com/2019/01/09/FL3ESf.png
        url: https://www.zhujiboke.com/
      - name: shansan
        avatar: https://img.vim-cn.com/8f/e4fa12e70f63550b3779d901103c67cefabfca.jpg
        url: https://shan333.cn
      - name: Whoer
        avatar: https://img.vim-cn.com/1b/f5cfbccb67f161973528bed7d372173cb4fb8c
        url: https://whoer.net/zh
      - name: cppreference
        avatar: https://s2.ax1x.com/2019/06/19/VXJMPx.jpg
        url: https://zh.cppreference.com/w/%E9%A6%96%E9%A1%B5
      - name: 网站缩略图生成
        icon: fas fa-camera
        url: thumbnail/
      - name: 让我帮你百度
        icon: fas fa-search
        url: trytobaidu/
      - name: 心声
        desc: 自言自语
        icon: fas fa-quran
        url: I_want_to_tell_me/
  custom_nav:
    class: grid
    display: [desktop, mobile]
    header:
      icon: fas fa-map-signs
      title: 站内导航
      url:
    rows:
      - name: 近期文章
        icon: fas fa-clock
        url: /
      - name: 文章归档
        icon: fas fa-archive
        url: archives/
        rel: nofollow
      - name: Github
        icon: fas fa-code-branch
        url: https://github.com/yeshan333
      - name: 我的友链
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: 主题文档
        icon: fas fa-book
        url: https://volantis.js.org/theme-settings/
        rel: nofollow
      - name: 关于小站
        icon: fas fa-info-circle
        url: about/
        rel: nofollow
  my_follow:
    class: list
    header:
      title: 我的关注
      icon: fas fa-thumbs-up
    rows:
      - name: Python Web入坑指南
        avatar: https://python-web-guide.readthedocs.io/zh/latest/_static/favicon.ico
        url: https://python-web-guide.readthedocs.io/zh/latest/
      - name: 国光
        avatar: https://i.loli.net/2020/03/14/DsAaP2hFqeuNOEo.png
        desc: 跟着混 Web 安全
        url: https://www.sqlsec.com/
      - name: 数据科学思维导图笔记
        url: https://woaielf.github.io/
        avatar: https://img.vim-cn.com/e9/5fce67298509e2df8594df95e10e957bc3fc09.png
      - name: Python术语对照表
        url: https://docs.python.org/zh-cn/3/glossary.html
        avatar: https://img.vim-cn.com/9e/e6cf0e86b514e0de34a5df49526df444a6b647.gif
      - name: Python运行时服务
        avatar: https://img.vim-cn.com/9e/e6cf0e86b514e0de34a5df49526df444a6b647.gif
        url: https://docs.python.org/zh-cn/3/library/python.html
      - name: draw.io
        avatar: https://i.loli.net/2020/03/14/LyEWzxKN4BfvFMh.png
        url: https://www.draw.io/
        desc: diagram




footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright, beian]
  social:
    - icon: fas fa-envelope
      url: mailto:1329441308@qq.com
    - icon: fab fa-github
      url: https://github.com/yeshan333?tab=repositories
    - icon: fas fa-music
      url: https://music.163.com/#/my/m/music/playlist?id=2617691792
    - icon: fab fa-zhihu
      url: https://www.zhihu.com/people/si-kong-ji-54/activities
    - icon: fas fa-rss
      url: https://yeshan333.github.io/sitemap.xml
  copyright: '[Copyright © 2018-2020 ShanSan](https://shansan.top)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  # br: '<br>'
  beian: '[桂ICP备19000444号](http://www.beian.miit.gov.cn/)'


############################### SEO ###############################
seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter


############################### Plugins ###############################
plugins:
  # Required plugins:
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js

  ######## Plugins to improve loading speed:
  # Preload (The menu's url must end with ‘/’)
  instant_page: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0.2.4/js/instant_page.js

  ######## Plugins to optimize the experience:
  # Picture Zoom
  fancybox:
    css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # Page Scrolling Animation
  scrollreveal: #https://cdn.jsdelivr.net/npm/scrollreveal@4.0.5/dist/scrollreveal.min.js

  # Codeblock Copy Button
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  ######## Plugins for SEO:
  # Traffic statistics (very slow loading)
  busuanzi: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

  # npm i --save hexo-wordcount
  wordcount: # true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # Typing Effects
  comment_typing: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0.2.4/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    duration: 20000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    white_text: #true     # Whether the picture is dark (adjust the text to white)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
      # # Suggest white_text: true
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 3175833810    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 340px # list max height
    list_folded: true




############################### Comments ###############################
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, disqus, gitalk, livere
  valine:
    appId: S687AsCjGJKTPIvUJ8aPNX49-gzGzoHsz # your appId
    appKey: bCwg3QuIfGytbeYw58L7ofRq # your appKey
    js: https://cdn.jsdelivr.net/gh/yeshan333/jsDelivrCDN@0.1/volantis.js # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0.2.4/js/valine.js
    path: # All pages use the same path (share the same comments data)
    meta: nick,mail,link #valine comment header info
    placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
    avatar: mp # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    verify: true # valine verify code (true/false)
    notify: true # valine mail notify (true/false)
    lang: zh-cn
    highlight: true
    visitor: false # unavailable for now...
  disqus:
    shortname:
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin: # []
  livere:
    uid:




############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i -S hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0.2.4/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:
