pages:
  # 友链页面配置
  friends:
    layout_scheme: sites # simple: 简单布局, traditional: 传统布局,  sites: 网站卡片布局

############################### Comments ############################### > start
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: waline # valine, twikoo, waline, minivaline, disqus, disqusjs, gitalk, vssue, livere, isso, hashover
  # Valine
  # https://valine.js.org/
  valine:
    # js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
    path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是valine的问题
    placeholder: 快来评论吧~  # 评论占位提示
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder emojiCDN emojiMaps] 选项
    appId: S687AsCjGJKTPIvUJ8aPNX49-gzGzoHsz # your appId
    appKey: bCwg3QuIfGytbeYw58L7ofRq # your appKey
    meta: [nick,mail,link] # valine comment header info
    requiredFields: [nick, mail]
    enableQQ: true # Unstable avatar link
    recordIP: false # Record commenter IP
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    mathJax: false
  waline:
      js: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
      path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是waline的问题
      placeholder: 快来评论吧~  # 评论占位提示
      imageHosting: https://7bu.top/api/upload # 图床api（默认使用去不图床）
      # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder uploadImage] 选项
      serverURL: https://yeshan333-waline.vercel.app # Waline 的服务端地址（必填） 测试用地址: https://waline-ruddy.vercel.app
############################### Comments ############################### > end

############################### Navigation Bar ############################### > start
# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title: ShanSan
  menu:
    - name: 博文
      icon: fas fa-rss
      url: /
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
    - name: 与我相关
      icon: fas fa-ellipsis-v
      rows:
        - name: Github
          icon: fab fa-github-square
          url: https://github.com/yeshan333
        - name: slides
          icon: fab fa-slideshare
          url: https://slide.shan333.cn
        - name: notes
          icon: far fa-sticky-note
          url: https://shansan.top/knowledge-base/
        - name: Monitor
          url: https://stats.uptimerobot.com/OknEPcNEVr
    - name: 云原生
      icon: fas fa-cloud
      url: cloud-native/
    # - name: 中国蟒
    #   icon: fab fa-python
    #   url: PyChina/

  search: 寻你所想   # Search bar placeholder
############################### Navigation Bar ############################### > end

############################### Color Scheme ############################### > start
color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: '#197b30'
    # 链接色
    link: '#2196f3'
    # 按钮色
    button: '#44D7B6'
    # 鼠标放到交互元素上时的色
    hover: '#ff5722'
    # 主题色块内部的文字颜色
    inner: '#fff'
    # 选中区域文字的背景颜色
    selection: 'alpha(#2196f3, 0.2)'
  # ------------
  # 亮色主题（默认）
  light:
    # 网站背景色
    site_bg: '#f4f4f4'
    # 网站背景上的文字
    site_inner: '#fff'
    # 网站页脚文字
    site_footer: '#666'

    # 卡片背景色
    card: '#fff'
    # 卡片上的普通文字
    text: '#444'

    # 区块和代码块背景色
    block: '#f6f6f6'
    # 代码块高亮时的背景色
    codeblock: '#FFF7EA'
    # 行内代码颜色
    inlinecode: '#c74f00'

    # 文章部分
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#333'
    h4: '#444'
    h5: '#555'
    h6: '#666'
    p: '#444'

    # 列表文字
    list: '#666'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #000, 80)'
    # 辅助性文字
    meta: '#888'
  # ------------
  # 暗色主题
  dark:
    # 网站背景色
    site_bg: '#222'
    # 网站背景上的文字
    site_inner: '#eee'
    # 网站页脚文字
    site_footer: '#aaa'
    # 卡片背景色
    card: '#333'
    # 卡片上的普通文字
    text: '#eee'

    # 区块和代码块背景色
    block: '#3a3a3a'
    # 代码块高亮时的背景色
    codeblock: '#343a3c'
    # 行内代码颜色
    inlinecode: '#D56D28'

    # 文章部分
    h1: '#eee'
    h2: '#eee'
    h3: '#ddd'
    h4: '#ddd'
    h5: '#ddd'
    h6: '#ddd'
    p: '#bbb'

    # 列表文字
    list: '#aaa'
    # 列表 hover 时的文字
    list_hl: 'mix($color-theme, #fff, 80)'
    # 辅助性文字
    meta: '#888'
    # 夜间图片亮度
    brightness: 70%
############################### Color Scheme ############################### > end

############################### Cover ############################### > start
cover:
  height_scheme: full # full, half
  layout_scheme: dock # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  # background: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
  background: https://cdn.jsdelivr.net/gh/ssmath/picgo-pic/img/20210310142425.png # https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  logo: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-Cover@3x.png
  title: 'More & Less'
  subtitle: 'created by yeshan333'
  search: 寻你所想 # search bar placeholder
  features:
    - name: 博文
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
    - name: 关于我
      icon:
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0.1/assets/svg/1f0cf.svg
      url: about/
    - name: 友链
      icon: #
      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: friends/
############################### Cover ############################### > end

site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright, beian]
  social:
    - icon: fas fa-envelope
      url: mailto:1329441308@qq.com
    - icon: fab fa-github
      url: https://github.com/yeshan333?tab=repositories
    - icon: fas fa-music
      url: https://music.163.com/#/my/m/music/playlist?id=2617691792
    - icon: fab fa-zhihu
      url: https://www.zhihu.com/people/si-kong-ji-54/activities
    - icon: fas fa-rss
      url: https://yeshan333.github.io/rss2.xml
  copyright: '[Copyright © 2018-2022 ShanSan](https://shansan.top)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'
  beian: '[桂ICP备19000444号](https://beian.miit.gov.cn/)'

############################### Search ############################### > start
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  js: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2.6.4/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:
############################### Search ############################### > end

############################### Sidebar ############################### > start
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, webinfo, category, tagcloud, wonderful_link, donate, my_follow]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn/try20200311205451.jpg
      shape: rectangle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fas fa-envelope
          url: mailto:1329441308@qq.com
        - icon: fab fa-github
          url: https://github.com/yeshan333?tab=repositories
        - icon: fas fa-music
          url: https://music.163.com/#/my/m/music/playlist?id=2617691792
        - icon: fab fa-zhihu
          url: https://www.zhihu.com/people/si-kong-ji-54/activities
        - icon: fas fa-rss
          url: https://yeshan333.github.io/rss2.xml
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 1
      max_depth: 5
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'

    # ---------------------------------------
    # qrcode widget
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: # Automatic height if not set
      images:
        - https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn@master/mmqrcode1583939866281.png
        - https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn@master/qrcode_1583939933465.jpg
    # ---------------------------------------
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop, mobile]
      header:
        icon: fas fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2018/08/19'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: false
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          service: busuanzi  # busuanzi, leancloud
          siteuv:
            enable: false
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'

    wonderful_link:
        class: list
        display: [desktop, mobile] # [desktop, mobile]
        header:
          icon: fas fa-medal
          title: 精选链接
          url:
        rows:
          - name: Volantis
            desc: Hexo博客主题
            icon: fas fa-cube
            url: https://volantis.js.org/
          - name: 关于我 / 留言板
            icon: fas fa-comment-dots
            url: /about/
          - name: Collect
            icon: fab fa-delicious
            url: /Collect/
          - name: shan_pic
            icon: fas fa-images
            url: https://img.shan333.cn
          - name: 每日天文一图
            avatar: https://apod.nasa.gov/favicon.ico
            url: https://apod.nasa.gov/apod/astropix.html
          - name: Carbon
            avatar: https://img.vim-cn.com/76/a8416146154b60cbaa432ad3cf3b919190e1d8
            url: https://carbon.now.sh
          - name: 雨落无声
            avatar: https://s2.ax1x.com/2019/01/09/FL3ESf.png
            url: https://www.zhujiboke.com/
          - name: shansan
            avatar: https://img.vim-cn.com/8f/e4fa12e70f63550b3779d901103c67cefabfca.jpg
            url: https://shan333.cn
          - name: Whoer
            avatar: https://img.vim-cn.com/1b/f5cfbccb67f161973528bed7d372173cb4fb8c
            url: https://whoer.net/zh
          - name: cppreference
            avatar: https://s2.ax1x.com/2019/06/19/VXJMPx.jpg
            url: https://zh.cppreference.com/w/%E9%A6%96%E9%A1%B5
          - name: 网站缩略图生成
            icon: fas fa-camera
            url: thumbnail/
          - name: 让我帮你百度
            icon: fas fa-search
            url: trytobaidu/
          - name: 心声
            desc: 自言自语
            icon: fas fa-quran
            url: I_want_to_tell_me/

    my_follow:
      class: list
      header:
        title: 我的关注
        icon: fas fa-thumbs-up
      rows:
        - name: Python Web入坑指南
          avatar: https://python-web-guide.readthedocs.io/zh/latest/_static/favicon.ico
          url: https://python-web-guide.readthedocs.io/zh/latest/
        - name: 国光
          avatar: https://i.loli.net/2020/03/14/DsAaP2hFqeuNOEo.png
          desc: 跟着混 Web 安全
          url: https://www.sqlsec.com/
        - name: 数据科学思维导图笔记
          url: https://woaielf.github.io/
          avatar: https://img.vim-cn.com/e9/5fce67298509e2df8594df95e10e957bc3fc09.png
        - name: Python术语对照表
          url: https://docs.python.org/zh-cn/3/glossary.html
          avatar: https://img.vim-cn.com/9e/e6cf0e86b514e0de34a5df49526df444a6b647.gif
        - name: Python运行时服务
          avatar: https://img.vim-cn.com/9e/e6cf0e86b514e0de34a5df49526df444a6b647.gif
          url: https://docs.python.org/zh-cn/3/library/python.html
        - name: draw.io
          avatar: https://i.loli.net/2020/03/14/LyEWzxKN4BfvFMh.png
          url: https://www.draw.io/
          desc: diagram
############################### Sidebar ############################### > end

############################### Article Layout ############################### > start
# 文章布局
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show author
    author: true # true, false
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, date, tags] #启用评论数量需在此添加
    # ----------------
    # 文章页脚组件
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fas fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 相关文章，需要安装插件 (for layout: post)
      # npm i hexo-related-popular-posts
      related_posts:
        enable: false
        title: 相关文章
        icon: fas fa-bookmark
        max_count: 5
        # 设为空则不使用文章头图
        placeholder_img: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
      # ----------------
      # 版权声明组件 (for layout: post)
      copyright:
        enable: true
        permalink: '本文永久链接是：'
        content:
          - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
          # - permalink
          - '我的博客即将同步至腾讯云+社区，邀请大家一同入驻：[https://cloud.tencent.com/developer/support-plan?invite_code=1utoln9pyvwqu](https://cloud.tencent.com/developer/support-plan?invite_code=1utoln9pyvwqu)'
      # ----------------
      # 打赏组件 (for layout: post)
      donate:
        enable: false
        images:
          - https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn@master/mmqrcode1583939866281.png
          - https://cdn.jsdelivr.net/gh/ssmath/images-assets-cdn@master/qrcode_1583939933465.jpg
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [updated, tags, share]
    # meta library
    meta_library:
      # 默认文章作者（可在 _data/author.yaml 中增加其他作者，并在 front-matter 中设置）
      # https://volantis.js.org/advanced-settings/#多人协同
      author:
        avatar: https://z3.ax1x.com/2021/11/07/I1qTFx.png
        name: yeshan333
        url: https://github.com/yeshan333
      # 文章创建日期
      date:
        icon: fas fa-calendar-alt
        title: '首发于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fas fa-edit
        title: '更新于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fas fa-folder-open
      # 文章浏览计数
      counter:
        icon: fas fa-eye
        unit: '次浏览'
      # 文章评论数量：支持 valine和waline
      valinecount:
        icon: fas fa-comment-dots
        desc: '' # 条评论
      walinecount:
        icon: fas fa-comment-dots
        desc: '' # 条评论
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fas fa-keyboard
        icon_duration: fas fa-hourglass-half
      # 文章标签
      tags:
        icon: fas fa-hashtag
      # 分享
      share:
        - id: qq
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
        - id: qzone
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
        - id: weibo
          img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
        - id: # qrcode # 当id为qrcode时需要安装插件  npm i hexo-helper-qrcode
          img: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/wechat.png
        - id: # telegram
          img: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png
############################### Article Layout ############################### > end

############################### Plugins ############################### > start
plugins:
  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: true
    js:
      aplayer: https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      meting: https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 6729508229    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 320px # list max height
    list_folded: true

  # Codeblock Copy Button
  clipboard:
    enable: true
    js: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  # 图片懒加载
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true
    js: https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.1.0/dist/lazyload.min.js
    onlypost: false
    loadingImg: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@3/img/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
    blurIn: true # 模糊加载效果 （loadingImg为空时有效）

  pjax:
    enable: false
    cover: true          # 封面是否pjax处理 false：每次切换页面封面都重载，适合封面较少的情况 true：封面经过Pjax处理，适合封面较多的情况
    timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    animation: false # false, nprogress, circle
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - '/artitalk/'     # artitalk 不支持 pjax
      # - '/bb/'           # bbtalk 不支持 pjax
############################### Plugins ############################### > end