# 网站图标
favicon: https://s1.ax1x.com/2022/10/09/xJ7yMF.png

import:
  link:
    - <link rel='stylesheet' href='https://at.alicdn.com/t/c/font_4475507_e8kaw9xmult.css'>
  script:
    - <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/yeshan333/jsDelivrCDN/piao.js" />
    - <script type="text/javascript" src="https://cdn.staticfile.org/jquery/1.7.2/jquery.min.js" />
    - <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/yeshan333/jsDelivrCDN/attatkmouse.js" />
    - <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/yeshan333/jsDelivrCDN/clearbit.js" />
    - <script async defer data-domain="shansan.top" src="https://plausible.io/js/plausible.js" />

hexinjiazhiguan: true

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ShanSan
subtitle: 个人博客
description: ShanSan's Blog
keywords: [ShanSan, Cloudys, shan333, shansan]
author: ShanSan
language:
  - zh-CN
  - en
  - zh-TW
# timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://yeshan333.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis576

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: git@github.com:yeshan333/yeshan333.github.io.git
    branch: master
  - type: baidu_url_submitter


# https://github.com/huiwang/hexo-baidu-url-submit
baidu_url_submit:
  count: 10 # 提交最新的 10 链接
  host: yeshan333.github.io # 在百度站长平台中注册的域名
  token: Z3H2nzCjpaxA9Ssm # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里

baidu_push: true

# 文章锁
# https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md
encrypt:
  enable: false

sitemap:
  path: sitemap.xml
  tag: false
  category: false

# https://github.com/hexojs/hexo-generator-feed
feed:
  enable: true
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss2.xml
  limit: 33
  hub:
  content: false
  content_limit: 333
  content_limit_delim: ' '
  order_by: -date
  icon: https://ospy.shan333.cn/blog/blog.avatar.jpg
  autodiscovery: true
  template:

aplayer:
  meting: true