############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: # 把对应的那一行注释掉就使用本地的文件
    # css:
      # style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/css/style.css
    js:
      # app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/js/app.js
      # search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/js/search.js
      # volantis: https://cdn.jsdelivr.net/gh/yeshan333/volantis@1.0/js/volantis.min.js



############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true
busuanzi: true
# fastclick: true



############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true      # 是否启用
  color: '#1BCDFC'  # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 2615636388    # 歌曲/专辑/歌单 ID
  volume: 0.7       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
avatar_placeholder: /img/002.jpg

# 日期格式 http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # 文章发布日期的格式
updated_date_format: 'll' # 文章更新日期的格式

# 幻灯片
backstretch:
  position: cover  # cover: 封面背景   full: 整个网页背景
  duration: 6000 # 持续时间（毫秒）
  fade: 2500     # 渐变（毫秒）
  images:
    - https://img.vim-cn.com/6d/a0c9e6f9efad8b731cb7376504bd10d79d2053.jpg



############################### 自定义 ###############################
# page的封面
# cover:
  scheme: search    # 后期将会提供多种封面方案
  height: half      # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  title: "ShanSan"
  # logo: assets/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  search_placeholder: '搜索'
  # 主页封面菜单
  features:
    - name: 博文
      icon: fas fa-rss
      url: /
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
      rel: nofollow


# 桌面端导航栏菜单
menu_desktop:
  - name: 主页
    icon: fas fa-home
    url: /
  - name: 博客
    icon: fas fa-rss
    url: /
  - name: 归档
    icon: fas fa-archive
    url: archives/
  - name: Github
    icon: fab fa-github-square
    url: https://github.com/yeshan333
  - name: 关于
    icon: fas fa-user
    url: about/
  - name: friends
    icon: fas fa-users
    url: friends/
  - name: slides
    icon: fab fa-slideshare
    url: https://slide.shan333.cn
  - name: 中国蟒
    icon: fab fa-python
    url: PyChina/


# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: 近期文章
    icon: fas fa-clock
    url: /
  - name: 文章归档
    icon: fas fa-archive
    url: archives/
    rel: nofollow
  - name: Github
    icon: fas fa-code-branch
    url: https://github.com/yeshan333
  - name: 我的友链
    icon: fas fa-link
    url: friends/
    rel: nofollow
  - name: 主题文档
    icon: fas fa-book
    url: https://xaoxuu.com/wiki/material-x/
    rel: nofollow
  - name: 关于小站
    icon: fas fa-info-circle
    url: about/
    rel: nofollow
  - name: 声明
    icon: fas fa-bullhorn
    url: Statement/
    rel: nofollow

# 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
# 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
# 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
meta:
  header: [title, author, date, categories, counter, top]
  footer: [updated, tags, share]

# 主体元素，你也可以在页面的Front-matter中设置
body: [article, comments]

# 侧边栏小部件，默认按下面给定的顺序全部显示，文章中还可以自定义显示一部分以及顺序
sidebar:
  - widget: author
    avatar: https://shansan.top/img/002.jpg
    jinrishici: true
    social: true
  - widget: toc
  - widget: grid
    icon: fas fa-map-signs
    title: 站内导航
    more:
      icon: fas fa-quran
      url: I_want_to_tell_me/
    rows:
      - name: 近期文章
        icon: fas fa-clock
        url: /
      - name: 文章归档
        icon: fas fa-archive
        url: archives/
        rel: nofollow
      - name: Github
        icon: fas fa-code-branch
        url: https://github.com/yeshan333
      - name: 我的友链
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: 主题文档
        icon: fas fa-book
        url: https://xaoxuu.com/wiki/material-x/
        rel: nofollow
      - name: 关于小站
        icon: fas fa-info-circle
        url: about/
        rel: nofollow
  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: categories/
      rel: nofollow
  - widget: tagcloud
    icon: fas fa-fire
    more:
      icon: fas fa-expand-arrows-alt
      url: tags/
      rel: nofollow
  - widget: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts
  - widget: music
    icon: fas fa-compact-disc
    title: "最近在听"
    more:
      icon: far fa-heart
      url: https://music.163.com/#/user/home?id=63035382
      rel: external nofollow noopener noreferrer
      target: _blank
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 2617691792     # 歌曲/专辑/歌单 ID
  - widget: list
    icon: fas fa-medal
    title: 精选链接
    rows:
      - name: Material X
        desc: Hexo博客主题
        icon: fas fa-cube
        url: https://xaoxuu.com/wiki/material-x/
      - name: 关于我 / 留言板
        icon: fas fa-comment-dots
        url: /about/
      - name: Collect
        icon: fab fa-delicious
        url: /Collect/
      - name: shan_pic
        icon: fas fa-images
        url: https://img.shan333.cn
      - name: 每日天文一图
        avatar: https://apod.nasa.gov/favicon.ico
        url: https://apod.nasa.gov/apod/astropix.html
      - name: Carbon
        avatar: https://img.vim-cn.com/76/a8416146154b60cbaa432ad3cf3b919190e1d8
        url: https://carbon.now.sh
      - name: 雨落无声
        avatar: https://s2.ax1x.com/2019/01/09/FL3ESf.png
        url: https://www.zhujiboke.com/
      - name: shansan
        avatar: https://img.vim-cn.com/8f/e4fa12e70f63550b3779d901103c67cefabfca.jpg
        url: https://shan333.cn
      - name: Whoer
        avatar: https://img.vim-cn.com/1b/f5cfbccb67f161973528bed7d372173cb4fb8c
        url: https://whoer.net/zh
      - name: cppreference
        avatar: https://s2.ax1x.com/2019/06/19/VXJMPx.jpg
        url: https://zh.cppreference.com/w/%E9%A6%96%E9%A1%B5
      - name: 网站缩略图生成
        icon: fas fa-camera
        url: thumbnail/
      - name: 让我帮你百度
        icon: fas fa-search
        url: trytobaidu/
  - widget: list
    icon: fas fa-thumbs-up
    title: 我的关注
    rows:
      - name: Python Web入坑指南
        avatar: https://python-web-guide.readthedocs.io/zh/latest/_static/favicon.ico
        url: https://python-web-guide.readthedocs.io/zh/latest/
      - name: 国光
        avatar: https://image.3001.net/images/20190329/15538458216510.png
        desc: Web安全
        url: https://www.sqlsec.com/
      - name: 数据科学思维导图笔记
        url: https://woaielf.github.io/
        avatar: https://img.vim-cn.com/e9/5fce67298509e2df8594df95e10e957bc3fc09.png
      - name: Python术语对照表
        url: https://docs.python.org/zh-cn/3/glossary.html
        avatar: https://img.vim-cn.com/9e/e6cf0e86b514e0de34a5df49526df444a6b647.gif
      - name: Python运行时服务
        avatar: https://img.vim-cn.com/9e/e6cf0e86b514e0de34a5df49526df444a6b647.gif
        url: https://docs.python.org/zh-cn/3/library/python.html
      - name: draw.io
        url: https://www.draw.io/

# 社交信息
social:
  - icon: fas fa-envelope
    url: mailto:1329441308@qq.com
  - icon: fab fa-github
    url: https://github.com/yeshan333?tab=repositories
  - icon: fas fa-music
    url: https://music.163.com/#/my/m/music/playlist?id=2617691792
  - icon: fab fa-zhihu
    url: https://www.zhihu.com/people/si-kong-ji-54/activities
  - icon: fas fa-rss
    url: https://yeshan333.github.io/sitemap.xml


# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  # - id: qrcode
  #   name: 微信
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  # - id: qrcode
  #   name: QRcode
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png



# footer: '页脚文字，支持[markdown](/)'


############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# gitalk: 要使用哪个请复制到根目录配置文件！
#   clientID: 你的clientID
#   clientSecret: 你的clientSecret
#   repo: 你的repo名
#   owner: 你的GitHub名
#   admin: [] 至少填写你的GitHub名
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey


############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
