name: Site CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # from: https://github.com/actions/checkout
      - name: Checkout Repository main branch
        uses: actions/checkout@main

      # from: https://github.com/actions/setup-node
      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: "12.x"

      - name: Setup Hexo Blog Dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: Add SSH private key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT

      - name: Release GitHub Pages
        run: |
          git config --global user.email "1329441308@qq.com"
          git config --global user.name "yeshan333"
          git clone git@github.com:yeshan333/yeshan333.github.io.git .deploy_git
          chmod 755 -R .deploy_git
          hexo clean
          hexo generate
          hexo deploy

      # from https://github.com/yeshan333/rsync-deploy-action
      - name: Release blog to tencentyun Lighthouse Instance (Yvette)
        uses: yeshan333/rsync-deploy-action@v1.0.0
        with:
          ssh_login_username: ${{ secrets.SSH_LOGIN_USERNAME }}
          remote_server_ip: ${{ secrets.REMOTE_SERVER_IP }}
          ssh_port: ${{ secrets.SSH_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source_path: ./.deploy_git/*
          destination_path: ~/shan333.cn
          rsync_args: --exclude="./.deploy_git/.git/*"

      - name: Release to Tecentyun Lighthouse Instance
        uses: yeshan333/rsync-deploy-action@v1.0.0
        with:
          ssh_login_username: ${{ secrets.SSH_LOGIN_USERNAME }}
          remote_server_ip: ${{ secrets.REMOTE_BACKUP_SERVER_IP }}
          ssh_port: ${{ secrets.BACKUP_SSH_PORT }}
          ssh_private_key: ${{ secrets.SSH_BACKUP_PRIVATE_KEY }}
          source_path: ./.deploy_git/*
          destination_path: ~/shan333.cn
          rsync_args: --exclude="./.deploy_git/.git/*"
